import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='h-screen w-screen p-8 bg-gray-600'>
                <h1 className='text-2xl text-white'>Lift Log Web</h1>
            </main>
        </>
    )
}
